package tdh.platform.export.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ExportTemplateExample {
    /**
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method corresponds to the database table export_template
	 * @mbggenerated
	 */
	public ExportTemplateExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method corresponds to the database table export_template
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method corresponds to the database table export_template
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method corresponds to the database table export_template
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method corresponds to the database table export_template
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method corresponds to the database table export_template
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method corresponds to the database table export_template
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method corresponds to the database table export_template
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method corresponds to the database table export_template
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method corresponds to the database table export_template
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method corresponds to the database table export_template
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table export_template
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("exportTemplate.id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("exportTemplate.id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("exportTemplate.id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("exportTemplate.id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("exportTemplate.id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("exportTemplate.id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("exportTemplate.id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("exportTemplate.id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("exportTemplate.id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("exportTemplate.id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("exportTemplate.id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("exportTemplate.id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andClassNameIsNull() {
			addCriterion("exportTemplate.class_name is null");
			return (Criteria) this;
		}

		public Criteria andClassNameIsNotNull() {
			addCriterion("exportTemplate.class_name is not null");
			return (Criteria) this;
		}

		public Criteria andClassNameEqualTo(String value) {
			addCriterion("exportTemplate.class_name =", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameNotEqualTo(String value) {
			addCriterion("exportTemplate.class_name <>", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameGreaterThan(String value) {
			addCriterion("exportTemplate.class_name >", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameGreaterThanOrEqualTo(String value) {
			addCriterion("exportTemplate.class_name >=", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameLessThan(String value) {
			addCriterion("exportTemplate.class_name <", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameLessThanOrEqualTo(String value) {
			addCriterion("exportTemplate.class_name <=", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameLike(String value) {
			addCriterion("exportTemplate.class_name like", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameNotLike(String value) {
			addCriterion("exportTemplate.class_name not like", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameIn(List<String> values) {
			addCriterion("exportTemplate.class_name in", values, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameNotIn(List<String> values) {
			addCriterion("exportTemplate.class_name not in", values, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameBetween(String value1, String value2) {
			addCriterion("exportTemplate.class_name between", value1, value2, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameNotBetween(String value1, String value2) {
			addCriterion("exportTemplate.class_name not between", value1, value2, "className");
			return (Criteria) this;
		}

		public Criteria andMethodNameIsNull() {
			addCriterion("exportTemplate.method_name is null");
			return (Criteria) this;
		}

		public Criteria andMethodNameIsNotNull() {
			addCriterion("exportTemplate.method_name is not null");
			return (Criteria) this;
		}

		public Criteria andMethodNameEqualTo(String value) {
			addCriterion("exportTemplate.method_name =", value, "methodName");
			return (Criteria) this;
		}

		public Criteria andMethodNameNotEqualTo(String value) {
			addCriterion("exportTemplate.method_name <>", value, "methodName");
			return (Criteria) this;
		}

		public Criteria andMethodNameGreaterThan(String value) {
			addCriterion("exportTemplate.method_name >", value, "methodName");
			return (Criteria) this;
		}

		public Criteria andMethodNameGreaterThanOrEqualTo(String value) {
			addCriterion("exportTemplate.method_name >=", value, "methodName");
			return (Criteria) this;
		}

		public Criteria andMethodNameLessThan(String value) {
			addCriterion("exportTemplate.method_name <", value, "methodName");
			return (Criteria) this;
		}

		public Criteria andMethodNameLessThanOrEqualTo(String value) {
			addCriterion("exportTemplate.method_name <=", value, "methodName");
			return (Criteria) this;
		}

		public Criteria andMethodNameLike(String value) {
			addCriterion("exportTemplate.method_name like", value, "methodName");
			return (Criteria) this;
		}

		public Criteria andMethodNameNotLike(String value) {
			addCriterion("exportTemplate.method_name not like", value, "methodName");
			return (Criteria) this;
		}

		public Criteria andMethodNameIn(List<String> values) {
			addCriterion("exportTemplate.method_name in", values, "methodName");
			return (Criteria) this;
		}

		public Criteria andMethodNameNotIn(List<String> values) {
			addCriterion("exportTemplate.method_name not in", values, "methodName");
			return (Criteria) this;
		}

		public Criteria andMethodNameBetween(String value1, String value2) {
			addCriterion("exportTemplate.method_name between", value1, value2, "methodName");
			return (Criteria) this;
		}

		public Criteria andMethodNameNotBetween(String value1, String value2) {
			addCriterion("exportTemplate.method_name not between", value1, value2, "methodName");
			return (Criteria) this;
		}

		public Criteria andFileNameIsNull() {
			addCriterion("exportTemplate.file_name is null");
			return (Criteria) this;
		}

		public Criteria andFileNameIsNotNull() {
			addCriterion("exportTemplate.file_name is not null");
			return (Criteria) this;
		}

		public Criteria andFileNameEqualTo(String value) {
			addCriterion("exportTemplate.file_name =", value, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameNotEqualTo(String value) {
			addCriterion("exportTemplate.file_name <>", value, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameGreaterThan(String value) {
			addCriterion("exportTemplate.file_name >", value, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameGreaterThanOrEqualTo(String value) {
			addCriterion("exportTemplate.file_name >=", value, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameLessThan(String value) {
			addCriterion("exportTemplate.file_name <", value, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameLessThanOrEqualTo(String value) {
			addCriterion("exportTemplate.file_name <=", value, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameLike(String value) {
			addCriterion("exportTemplate.file_name like", value, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameNotLike(String value) {
			addCriterion("exportTemplate.file_name not like", value, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameIn(List<String> values) {
			addCriterion("exportTemplate.file_name in", values, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameNotIn(List<String> values) {
			addCriterion("exportTemplate.file_name not in", values, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameBetween(String value1, String value2) {
			addCriterion("exportTemplate.file_name between", value1, value2, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameNotBetween(String value1, String value2) {
			addCriterion("exportTemplate.file_name not between", value1, value2, "fileName");
			return (Criteria) this;
		}

		public Criteria andRemarksIsNull() {
			addCriterion("exportTemplate.remarks is null");
			return (Criteria) this;
		}

		public Criteria andRemarksIsNotNull() {
			addCriterion("exportTemplate.remarks is not null");
			return (Criteria) this;
		}

		public Criteria andRemarksEqualTo(String value) {
			addCriterion("exportTemplate.remarks =", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksNotEqualTo(String value) {
			addCriterion("exportTemplate.remarks <>", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksGreaterThan(String value) {
			addCriterion("exportTemplate.remarks >", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksGreaterThanOrEqualTo(String value) {
			addCriterion("exportTemplate.remarks >=", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksLessThan(String value) {
			addCriterion("exportTemplate.remarks <", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksLessThanOrEqualTo(String value) {
			addCriterion("exportTemplate.remarks <=", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksLike(String value) {
			addCriterion("exportTemplate.remarks like", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksNotLike(String value) {
			addCriterion("exportTemplate.remarks not like", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksIn(List<String> values) {
			addCriterion("exportTemplate.remarks in", values, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksNotIn(List<String> values) {
			addCriterion("exportTemplate.remarks not in", values, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksBetween(String value1, String value2) {
			addCriterion("exportTemplate.remarks between", value1, value2, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksNotBetween(String value1, String value2) {
			addCriterion("exportTemplate.remarks not between", value1, value2, "remarks");
			return (Criteria) this;
		}

		public Criteria andDeletedIsNull() {
			addCriterion("exportTemplate.DELETED is null");
			return (Criteria) this;
		}

		public Criteria andDeletedIsNotNull() {
			addCriterion("exportTemplate.DELETED is not null");
			return (Criteria) this;
		}

		public Criteria andDeletedEqualTo(Byte value) {
			addCriterion("exportTemplate.DELETED =", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedNotEqualTo(Byte value) {
			addCriterion("exportTemplate.DELETED <>", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedGreaterThan(Byte value) {
			addCriterion("exportTemplate.DELETED >", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedGreaterThanOrEqualTo(Byte value) {
			addCriterion("exportTemplate.DELETED >=", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedLessThan(Byte value) {
			addCriterion("exportTemplate.DELETED <", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedLessThanOrEqualTo(Byte value) {
			addCriterion("exportTemplate.DELETED <=", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedIn(List<Byte> values) {
			addCriterion("exportTemplate.DELETED in", values, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedNotIn(List<Byte> values) {
			addCriterion("exportTemplate.DELETED not in", values, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedBetween(Byte value1, Byte value2) {
			addCriterion("exportTemplate.DELETED between", value1, value2, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedNotBetween(Byte value1, Byte value2) {
			addCriterion("exportTemplate.DELETED not between", value1, value2, "deleted");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeIsNull() {
			addCriterion("exportTemplate.CREATED_TIME is null");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeIsNotNull() {
			addCriterion("exportTemplate.CREATED_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeEqualTo(Date value) {
			addCriterion("exportTemplate.CREATED_TIME =", value, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeNotEqualTo(Date value) {
			addCriterion("exportTemplate.CREATED_TIME <>", value, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeGreaterThan(Date value) {
			addCriterion("exportTemplate.CREATED_TIME >", value, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("exportTemplate.CREATED_TIME >=", value, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeLessThan(Date value) {
			addCriterion("exportTemplate.CREATED_TIME <", value, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
			addCriterion("exportTemplate.CREATED_TIME <=", value, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeIn(List<Date> values) {
			addCriterion("exportTemplate.CREATED_TIME in", values, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeNotIn(List<Date> values) {
			addCriterion("exportTemplate.CREATED_TIME not in", values, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeBetween(Date value1, Date value2) {
			addCriterion("exportTemplate.CREATED_TIME between", value1, value2, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
			addCriterion("exportTemplate.CREATED_TIME not between", value1, value2, "createdTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeIsNull() {
			addCriterion("exportTemplate.UPDATED_TIME is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeIsNotNull() {
			addCriterion("exportTemplate.UPDATED_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeEqualTo(Date value) {
			addCriterion("exportTemplate.UPDATED_TIME =", value, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeNotEqualTo(Date value) {
			addCriterion("exportTemplate.UPDATED_TIME <>", value, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeGreaterThan(Date value) {
			addCriterion("exportTemplate.UPDATED_TIME >", value, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("exportTemplate.UPDATED_TIME >=", value, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeLessThan(Date value) {
			addCriterion("exportTemplate.UPDATED_TIME <", value, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeLessThanOrEqualTo(Date value) {
			addCriterion("exportTemplate.UPDATED_TIME <=", value, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeIn(List<Date> values) {
			addCriterion("exportTemplate.UPDATED_TIME in", values, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeNotIn(List<Date> values) {
			addCriterion("exportTemplate.UPDATED_TIME not in", values, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeBetween(Date value1, Date value2) {
			addCriterion("exportTemplate.UPDATED_TIME between", value1, value2, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeNotBetween(Date value1, Date value2) {
			addCriterion("exportTemplate.UPDATED_TIME not between", value1, value2, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andCreatedByIsNull() {
			addCriterion("exportTemplate.CREATED_BY is null");
			return (Criteria) this;
		}

		public Criteria andCreatedByIsNotNull() {
			addCriterion("exportTemplate.CREATED_BY is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedByEqualTo(Integer value) {
			addCriterion("exportTemplate.CREATED_BY =", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByNotEqualTo(Integer value) {
			addCriterion("exportTemplate.CREATED_BY <>", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByGreaterThan(Integer value) {
			addCriterion("exportTemplate.CREATED_BY >", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByGreaterThanOrEqualTo(Integer value) {
			addCriterion("exportTemplate.CREATED_BY >=", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByLessThan(Integer value) {
			addCriterion("exportTemplate.CREATED_BY <", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByLessThanOrEqualTo(Integer value) {
			addCriterion("exportTemplate.CREATED_BY <=", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByIn(List<Integer> values) {
			addCriterion("exportTemplate.CREATED_BY in", values, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByNotIn(List<Integer> values) {
			addCriterion("exportTemplate.CREATED_BY not in", values, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByBetween(Integer value1, Integer value2) {
			addCriterion("exportTemplate.CREATED_BY between", value1, value2, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByNotBetween(Integer value1, Integer value2) {
			addCriterion("exportTemplate.CREATED_BY not between", value1, value2, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByNameIsNull() {
			addCriterion("exportTemplate.CREATED_BY_NAME is null");
			return (Criteria) this;
		}

		public Criteria andCreatedByNameIsNotNull() {
			addCriterion("exportTemplate.CREATED_BY_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedByNameEqualTo(String value) {
			addCriterion("exportTemplate.CREATED_BY_NAME =", value, "createdByName");
			return (Criteria) this;
		}

		public Criteria andCreatedByNameNotEqualTo(String value) {
			addCriterion("exportTemplate.CREATED_BY_NAME <>", value, "createdByName");
			return (Criteria) this;
		}

		public Criteria andCreatedByNameGreaterThan(String value) {
			addCriterion("exportTemplate.CREATED_BY_NAME >", value, "createdByName");
			return (Criteria) this;
		}

		public Criteria andCreatedByNameGreaterThanOrEqualTo(String value) {
			addCriterion("exportTemplate.CREATED_BY_NAME >=", value, "createdByName");
			return (Criteria) this;
		}

		public Criteria andCreatedByNameLessThan(String value) {
			addCriterion("exportTemplate.CREATED_BY_NAME <", value, "createdByName");
			return (Criteria) this;
		}

		public Criteria andCreatedByNameLessThanOrEqualTo(String value) {
			addCriterion("exportTemplate.CREATED_BY_NAME <=", value, "createdByName");
			return (Criteria) this;
		}

		public Criteria andCreatedByNameLike(String value) {
			addCriterion("exportTemplate.CREATED_BY_NAME like", value, "createdByName");
			return (Criteria) this;
		}

		public Criteria andCreatedByNameNotLike(String value) {
			addCriterion("exportTemplate.CREATED_BY_NAME not like", value, "createdByName");
			return (Criteria) this;
		}

		public Criteria andCreatedByNameIn(List<String> values) {
			addCriterion("exportTemplate.CREATED_BY_NAME in", values, "createdByName");
			return (Criteria) this;
		}

		public Criteria andCreatedByNameNotIn(List<String> values) {
			addCriterion("exportTemplate.CREATED_BY_NAME not in", values, "createdByName");
			return (Criteria) this;
		}

		public Criteria andCreatedByNameBetween(String value1, String value2) {
			addCriterion("exportTemplate.CREATED_BY_NAME between", value1, value2, "createdByName");
			return (Criteria) this;
		}

		public Criteria andCreatedByNameNotBetween(String value1, String value2) {
			addCriterion("exportTemplate.CREATED_BY_NAME not between", value1, value2, "createdByName");
			return (Criteria) this;
		}

		public Criteria andUpdatedByIsNull() {
			addCriterion("exportTemplate.UPDATED_BY is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedByIsNotNull() {
			addCriterion("exportTemplate.UPDATED_BY is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedByEqualTo(Integer value) {
			addCriterion("exportTemplate.UPDATED_BY =", value, "updatedBy");
			return (Criteria) this;
		}

		public Criteria andUpdatedByNotEqualTo(Integer value) {
			addCriterion("exportTemplate.UPDATED_BY <>", value, "updatedBy");
			return (Criteria) this;
		}

		public Criteria andUpdatedByGreaterThan(Integer value) {
			addCriterion("exportTemplate.UPDATED_BY >", value, "updatedBy");
			return (Criteria) this;
		}

		public Criteria andUpdatedByGreaterThanOrEqualTo(Integer value) {
			addCriterion("exportTemplate.UPDATED_BY >=", value, "updatedBy");
			return (Criteria) this;
		}

		public Criteria andUpdatedByLessThan(Integer value) {
			addCriterion("exportTemplate.UPDATED_BY <", value, "updatedBy");
			return (Criteria) this;
		}

		public Criteria andUpdatedByLessThanOrEqualTo(Integer value) {
			addCriterion("exportTemplate.UPDATED_BY <=", value, "updatedBy");
			return (Criteria) this;
		}

		public Criteria andUpdatedByIn(List<Integer> values) {
			addCriterion("exportTemplate.UPDATED_BY in", values, "updatedBy");
			return (Criteria) this;
		}

		public Criteria andUpdatedByNotIn(List<Integer> values) {
			addCriterion("exportTemplate.UPDATED_BY not in", values, "updatedBy");
			return (Criteria) this;
		}

		public Criteria andUpdatedByBetween(Integer value1, Integer value2) {
			addCriterion("exportTemplate.UPDATED_BY between", value1, value2, "updatedBy");
			return (Criteria) this;
		}

		public Criteria andUpdatedByNotBetween(Integer value1, Integer value2) {
			addCriterion("exportTemplate.UPDATED_BY not between", value1, value2, "updatedBy");
			return (Criteria) this;
		}

		public Criteria andUpdatedByNameIsNull() {
			addCriterion("exportTemplate.UPDATED_BY_NAME is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedByNameIsNotNull() {
			addCriterion("exportTemplate.UPDATED_BY_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedByNameEqualTo(String value) {
			addCriterion("exportTemplate.UPDATED_BY_NAME =", value, "updatedByName");
			return (Criteria) this;
		}

		public Criteria andUpdatedByNameNotEqualTo(String value) {
			addCriterion("exportTemplate.UPDATED_BY_NAME <>", value, "updatedByName");
			return (Criteria) this;
		}

		public Criteria andUpdatedByNameGreaterThan(String value) {
			addCriterion("exportTemplate.UPDATED_BY_NAME >", value, "updatedByName");
			return (Criteria) this;
		}

		public Criteria andUpdatedByNameGreaterThanOrEqualTo(String value) {
			addCriterion("exportTemplate.UPDATED_BY_NAME >=", value, "updatedByName");
			return (Criteria) this;
		}

		public Criteria andUpdatedByNameLessThan(String value) {
			addCriterion("exportTemplate.UPDATED_BY_NAME <", value, "updatedByName");
			return (Criteria) this;
		}

		public Criteria andUpdatedByNameLessThanOrEqualTo(String value) {
			addCriterion("exportTemplate.UPDATED_BY_NAME <=", value, "updatedByName");
			return (Criteria) this;
		}

		public Criteria andUpdatedByNameLike(String value) {
			addCriterion("exportTemplate.UPDATED_BY_NAME like", value, "updatedByName");
			return (Criteria) this;
		}

		public Criteria andUpdatedByNameNotLike(String value) {
			addCriterion("exportTemplate.UPDATED_BY_NAME not like", value, "updatedByName");
			return (Criteria) this;
		}

		public Criteria andUpdatedByNameIn(List<String> values) {
			addCriterion("exportTemplate.UPDATED_BY_NAME in", values, "updatedByName");
			return (Criteria) this;
		}

		public Criteria andUpdatedByNameNotIn(List<String> values) {
			addCriterion("exportTemplate.UPDATED_BY_NAME not in", values, "updatedByName");
			return (Criteria) this;
		}

		public Criteria andUpdatedByNameBetween(String value1, String value2) {
			addCriterion("exportTemplate.UPDATED_BY_NAME between", value1, value2, "updatedByName");
			return (Criteria) this;
		}

		public Criteria andUpdatedByNameNotBetween(String value1, String value2) {
			addCriterion("exportTemplate.UPDATED_BY_NAME not between", value1, value2, "updatedByName");
			return (Criteria) this;
		}

		public Criteria andVersionIsNull() {
			addCriterion("exportTemplate.VERSION is null");
			return (Criteria) this;
		}

		public Criteria andVersionIsNotNull() {
			addCriterion("exportTemplate.VERSION is not null");
			return (Criteria) this;
		}

		public Criteria andVersionEqualTo(Integer value) {
			addCriterion("exportTemplate.VERSION =", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotEqualTo(Integer value) {
			addCriterion("exportTemplate.VERSION <>", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThan(Integer value) {
			addCriterion("exportTemplate.VERSION >", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
			addCriterion("exportTemplate.VERSION >=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThan(Integer value) {
			addCriterion("exportTemplate.VERSION <", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThanOrEqualTo(Integer value) {
			addCriterion("exportTemplate.VERSION <=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionIn(List<Integer> values) {
			addCriterion("exportTemplate.VERSION in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotIn(List<Integer> values) {
			addCriterion("exportTemplate.VERSION not in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionBetween(Integer value1, Integer value2) {
			addCriterion("exportTemplate.VERSION between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotBetween(Integer value1, Integer value2) {
			addCriterion("exportTemplate.VERSION not between", value1, value2, "version");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table export_template
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class corresponds to the database table export_template
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}